[keyboard]
bindings = [
  {key = "W", mods = "Command", chars = "\u001BW" },
  {key = "X", mods = "Command", chars = "\u001BX" },
  {key = 30, mods = "Command|Shift", chars = "\u001Bn" },
  {key = 33, mods = "Command|Shift", chars = "\u001Bp" },
  {key = "Z", mods = "Command", chars = "\u0001w" },
  {key = "T", mods = "Command", chars = "\u001Bt" },
  {key = "E", mods = "Command", chars = "\u001Be" },
  {key = "D", mods = "Command", chars = "\u001Bd" },
  # tmux resurrect plugin
  {key = "R", mods = "Command", chars = "\u0001\u0012" },
  {key = "S", mods = "Command", chars = "\u0001\u0013" },
  # move cursor per word
  {key = "Right", mods = "Command", chars = "\u001BF" },
  {key = "Left", mods = "Command", chars = "\u001BB" },
]
